.PHONY: all clean bst is_bst

all: clean
	g++ -std=c++11 -o bst bst.cpp

bst:
	g++ -std=c++11 -o bst bst.cpp

is_bst:
	g++ -std=c++11 -o is_bst is_bst.cpp

clean:
	rm -f a.out
	rm -f bst
	rm -f is_bst
