#
# Makefile for
# 	graph.cpp
# 	learning_cpp_hw3.cpp
# 	shortest_path.cpp
#

.PHONY : all graph hw sp clean

all: clean
	g++ -std=c++11 -ggdb3 -o graph  graph.cpp
	g++ -std=c++11 -ggdb3 -o hw3  learning_cpp_hw3.cpp
	g++ -std=c++11 -ggdb3 -o shortest_path  shortest_path.cpp

graph:
	g++ -std=c++11 -ggdb3 -o graph  graph.cpp
	
hw:
	g++ -std=c++11 -ggdb3 -o hw3  learning_cpp_hw3.cpp

sp:
	g++ -std=c++11 -ggdb3 -o shortest_path  shortest_path.cpp

clean:
	rm -f graph
	rm -f a.out
	rm -f hw3
	rm -f shortest_path
